version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: soccer_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: